export type Vegetable = {
  name: string;
  description: string;
  specifications: string[];
  sowing: string[];
  plantation: string[];
  harvest: string[];
  affinity: string[];
  bad_neighbors: string[];
};

export const vegetables: Vegetable[] = [
  {
    name: "Tomate",
    description:
      "Plante fruitière très populaire, nécessite beaucoup de lumière et de chaleur.",
    specifications: [
      "Besoin ensoleillement élevé",
      "Sensible au mildiou",
      "Croissance verticale",
    ],
    sowing: ["février", "mars", "avril"],
    plantation: ["avril", "mai", "juin"],
    harvest: ["juillet", "août", "septembre", "octobre"],
    affinity: ["Basilic", "Carotte", "Oignon"],
    bad_neighbors: ["Pomme de terre", "Fenouil"],
  },
  {
    name: "Basilic",
    description:
      "Herbe aromatique facile à cultiver, aime la chaleur et l'humidité.",
    specifications: [
      "Aime la chaleur",
      "Pousse rapide",
      "Aromatique puissante",
    ],
    sowing: ["mars", "avril", "mai"],
    plantation: ["mai", "juin"],
    harvest: ["juin", "juillet", "août", "septembre"],
    affinity: ["Tomate", "Poivron", "Aubergine"],
    bad_neighbors: ["Rue officinale"],
  },
  {
    name: "Persil",
    description:
      "Herbe aromatique résistante, pousse bien en intérieur ou extérieur.",
    specifications: [
      "Pousse lente",
      "Résistant au froid",
      "Aromatique universel",
    ],
    sowing: ["février", "mars", "avril", "mai", "juin", "juillet", "août"],
    plantation: ["avril", "mai", "juin", "juillet", "août", "septembre"],
    harvest: [
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
    ],
    affinity: ["Tomate", "Carotte", "Ciboulette"],
    bad_neighbors: ["Laitue", "Menthe"],
  },
  {
    name: "Laitue",
    description: "Légume-feuille rapide, aime les zones fraîches et ombragées.",
    specifications: [
      "Croissance rapide",
      "Sensible à la chaleur",
      "Feuillage tendre",
    ],
    sowing: [
      "février",
      "mars",
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
    ],
    plantation: [
      "mars",
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
    ],
    harvest: [
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
    ],
    affinity: ["Radis", "Carotte", "Fraise"],
    bad_neighbors: ["Persil"],
  },
  {
    name: "Ciboulette",
    description: "Plante vivace au goût fin, idéale en pot ou pleine terre.",
    specifications: ["Vivace", "Aime la mi-ombre", "Anti-insectes"],
    sowing: ["mars", "avril", "mai"],
    plantation: ["avril", "mai", "juin"],
    harvest: [
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
    ],
    affinity: ["Carotte", "Persil", "Pommier"],
    bad_neighbors: ["Haricot"],
  },
  {
    name: "Menthe",
    description: "Aromatique vigoureuse, à cultiver de préférence en pot.",
    specifications: ["Invasive", "Vivace", "Rafraîchissante"],
    sowing: ["mars", "avril", "mai"],
    plantation: ["avril", "mai", "juin"],
    harvest: ["mai", "juin", "juillet", "août", "septembre", "octobre"],
    affinity: ["Chou", "Pois", "Radis"],
    bad_neighbors: ["Persil", "Camomille"],
  },
  {
    name: "Épinard",
    description: "Légume-feuille nutritif, aime les zones fraîches.",
    specifications: [
      "Sensible à la chaleur",
      "Croissance rapide",
      "Feuilles tendres",
    ],
    sowing: ["février", "mars", "avril", "mai", "août", "septembre", "octobre"],
    plantation: ["mars", "avril", "mai", "septembre"],
    harvest: ["avril", "mai", "juin", "octobre", "novembre", "décembre"],
    affinity: ["Fraise", "Pois", "Radis"],
    bad_neighbors: ["Betterave"],
  },
  {
    name: "Radis",
    description: "Légume-racine à croissance rapide, idéal en balcon.",
    specifications: ["Pousse rapide", "Aime l’humidité", "Idéal débutant"],
    sowing: ["mars", "avril", "mai", "juin", "juillet", "août", "septembre"],
    plantation: [],
    harvest: [
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
    ],
    affinity: ["Carotte", "Laitue", "Épinard"],
    bad_neighbors: ["Chou"],
  },
  {
    name: "Carotte",
    description: "Légume-racine demandant un sol profond et meuble.",
    specifications: ["Racine longue", "Pousse lente", "Sensibles aux cailloux"],
    sowing: ["mars", "avril", "mai", "juin", "juillet"],
    plantation: [],
    harvest: ["juin", "juillet", "août", "septembre", "octobre", "novembre"],
    affinity: ["Poireau", "Ciboulette", "Laitue"],
    bad_neighbors: ["Aneth"],
  },
  {
    name: "Poivron",
    description: "Plante du soleil, idéale en pot exposé sud.",
    specifications: ["Besoin de chaleur", "Croissance lente", "Fruits colorés"],
    sowing: ["février", "mars", "avril"],
    plantation: ["mai", "juin"],
    harvest: ["juillet", "août", "septembre", "octobre"],
    affinity: ["Basilic", "Oignon", "Carotte"],
    bad_neighbors: ["Fenouil"],
  },
  {
    name: "Courgette",
    description: "Plante productive demandant de la place.",
    specifications: ["Gourmande en eau", "Pousse rapide", "Grand feuillage"],
    sowing: ["avril", "mai"],
    plantation: ["mai", "juin"],
    harvest: ["juin", "juillet", "août", "septembre"],
    affinity: ["Haricot", "Maïs", "Radis"],
    bad_neighbors: ["Pomme de terre"],
  },
  {
    name: "Thym",
    description: "Aromatique méditerranéenne, très résistante.",
    specifications: ["Vivace", "Aime la sécheresse", "Anti-insectes"],
    sowing: ["mars", "avril", "mai", "juin"],
    plantation: ["mai", "juin", "juillet"],
    harvest: [
      "janvier",
      "février",
      "mars",
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    affinity: ["Romarin", "Chou", "Lavande"],
    bad_neighbors: ["Coriandre"],
  },
  {
    name: "Romarin",
    description: "Plante ligneuse au parfum fort, peu exigeante.",
    specifications: ["Vivace", "Aime le soleil", "Peu d’arrosage"],
    sowing: ["mars", "avril", "mai"],
    plantation: ["avril", "mai", "juin"],
    harvest: [
      "janvier",
      "février",
      "mars",
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    affinity: ["Thym", "Sauge", "Chou"],
    bad_neighbors: ["Menthe"],
  },
  {
    name: "Concombre",
    description: "Plante grimpante gourmande, aime la chaleur.",
    specifications: [
      "Besoin d’un tuteur",
      "Gourmande en eau",
      "Sensibles au froid",
    ],
    sowing: ["avril", "mai"],
    plantation: ["mai", "juin"],
    harvest: ["juillet", "août", "septembre"],
    affinity: ["Haricot", "Tournesol", "Aneth"],
    bad_neighbors: ["Sauge"],
  },
  {
    name: "Oignon vert",
    description: "Plante rustique et rapide à pousser.",
    specifications: ["Peu d’entretien", "Rustique", "Utilisable entier"],
    sowing: ["février", "mars", "avril", "août", "septembre"],
    plantation: ["mars", "avril", "septembre"],
    harvest: ["mai", "juin", "juillet", "octobre"],
    affinity: ["Carotte", "Betterave", "Tomate"],
    bad_neighbors: ["Haricot"],
  },
  {
    name: "Cerfeuil",
    description: "Aromatique fine, proche du persil mais plus doux.",
    specifications: ["Délicat", "Aime la fraîcheur", "Anti-puceron"],
    sowing: ["mars", "avril", "mai", "juin", "juillet", "août"],
    plantation: ["avril", "mai", "juin", "juillet", "août"],
    harvest: ["mai", "juin", "juillet", "août", "septembre", "octobre"],
    affinity: ["Radis", "Laitue", "Épinard"],
    bad_neighbors: ["Persil"],
  },
  {
    name: "Coriandre",
    description: "Aromatique fragile, monte vite en graines.",
    specifications: [
      "Feuillage comestible",
      "Sensible à la chaleur",
      "Cycle court",
    ],
    sowing: ["avril", "mai", "juin"],
    plantation: ["mai", "juin", "juillet"],
    harvest: ["juin", "juillet", "août", "septembre"],
    affinity: ["Carotte", "Aneth", "Piment"],
    bad_neighbors: ["Thym", "Fenouil"],
  },
  {
    name: "Piment",
    description: "Plante fruitière colorée, aime le chaud et la lumière.",
    specifications: ["Besoin de chaleur", "Longue maturation", "Décoratif"],
    sowing: ["février", "mars", "avril"],
    plantation: ["mai", "juin"],
    harvest: ["juillet", "août", "septembre", "octobre"],
    affinity: ["Basilic", "Coriandre", "Tomate"],
    bad_neighbors: ["Fenouil"],
  },
  {
    name: "Betterave",
    description: "Légume racine sucré, facile à cultiver.",
    specifications: [
      "Feuilles comestibles",
      "Tolère la fraîcheur",
      "Couleur vive",
    ],
    sowing: ["mars", "avril", "mai", "juin"],
    plantation: ["avril", "mai", "juin", "juillet"],
    harvest: ["juin", "juillet", "août", "septembre", "octobre", "novembre"],
    affinity: ["Oignon", "Chou", "Salade"],
    bad_neighbors: ["Épinard"],
  },
  {
    name: "Roquette",
    description: "Salade au goût piquant, pousse rapidement.",
    specifications: ["Feuilles tendres", "Pousse rapide", "Aime la fraîcheur"],
    sowing: ["mars", "avril", "mai", "juin", "juillet", "août", "septembre"],
    plantation: ["avril", "mai", "juin", "juillet", "août", "septembre"],
    harvest: ["mai", "juin", "juillet", "août", "septembre", "octobre"],
    affinity: ["Radis", "Carotte", "Laitue"],
    bad_neighbors: ["Chou"],
  },
];
